name: hierarchical-classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - scikit-learn
  - pillow
  - ipywidgets
  - matplotlib
  - pip
  - pip:
      - tqdm
